#!/bin/bash

docker exec -it ctm-cifar10-best bash
conda activate ctm
cd /home/ubuntu/EighthArticle/consistency_models-main_ver3

MODEL_FLAGS="--data_name=afhq --class_cond=False --eval_interval=10000000 --save_interval=10000000 --num_classes=0 --eval_batch=16 --eval_fid=False --eval_similarity=False --check_dm_performance=False --log_interval=100 --intermediate_samples=True --sample_interval=10 --sampling_batch=2 --use_scale_shift_norm=False --image_size 256 --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --ctm_training=False --apply_adaptive_weight=False --diffusion_schedule_sampler=lognormal --training_mode=edm"
CKPT_FLAGS="--teacher_model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/author_ckpt/edm_cat256_ema.pt --data_dir=/home/ubuntu/dataset/AFHQ/train/cat"
export OMPI_COMM_WORLD_RANK=0
export OMPI_COMM_WORLD_LOCAL_RANK=0
export OMPI_COMM_WORLD_SIZE=8

mpiexec -n 8 --allow-run-as-root python cm_train.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ --microbatch=2 --global_batch_size=16 --lr=0.0004

python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=80 --stochastic_seed=False --save_format=png --use_MPI=True --sampler=exact --sampling_steps=1 --device_id=0 --training_mode=ctm

ABCI
MODEL_FLAGS="--data_name=afhq --class_cond=False --eval_interval=10000000 --save_interval=10000000 --num_classes=0 --eval_batch=16 --eval_fid=False --eval_similarity=False --check_dm_performance=False --log_interval=100 --intermediate_samples=True --sample_interval=10 --sampling_batch=2 --use_scale_shift_norm=False --image_size 256 --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --apply_adaptive_weight=False --diffusion_schedule_sampler=lognormal --training_mode=ctm"
python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/edit_v3.jpg --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/stroke/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,20 --device_id=0 --scale=0.02 --num_gradient_descent=10 --gamma=0.5

GAIA
ssh gaia
salloc --partition=project142-a100-v2 --ntasks=8 --ntasks-per-node=8 --gpus-per-node=8 --cpus-per-task=32 --time=60 --account=project142

source /etc/profile.d/modules.sh
module load singularity/3.5.3
module load openmpi/3.1.6
singularity run --nv /sample/pytorch/container/nvcr.io-nvidia-pytorch.21.10-py3.sif
cd /home/fp084243/EighthArticle/consistency_models-main_ver3
export OMPI_COMM_WORLD_RANK=0
export OMPI_COMM_WORLD_LOCAL_RANK=0
export OMPI_COMM_WORLD_SIZE=8
MODEL_FLAGS="--data_name=afhq --class_cond=False --eval_interval=10000000 --save_interval=10000000 --num_classes=0 --eval_batch=16 --eval_fid=False --eval_similarity=False --check_dm_performance=False --log_interval=100 --intermediate_samples=True --sample_interval=10 --sampling_batch=2 --use_scale_shift_norm=False --image_size 256 --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --apply_adaptive_weight=False --diffusion_schedule_sampler=lognormal --training_mode=ctm"
mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=1 --device_id=0 --training_mode=ctm
CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/samples/ --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=16 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --sampling_steps=40 --gamma=0.3 --device_id=0 --training_mode=ctm > log.txt 2>&1 &


CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python application_sample.py $MODEL_FLAGS --classifier_depth=2 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/256x256_classifier.pt --pretrained_feature_extractor=True --ref_image_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/ref_images/mawmaw1_v1.jpg --out_dir /home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke --model_path=/home/fp084243/EighthArticleExperimentalResults/AFHQ/author_ckpt/ema_0.999_065000.pt --batch_size=4 --eval_num_samples=4 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=stroke --ts=14,18 --scale=1.0 --num_gradient_descent=100 --gamma=1.0 --device_id=0 > log.txt 2>&1 &


scp gaia:/home/fp084243/EighthArticleExperimentalResults/AFHQ/stroke/ctm_stroke_sampler_40_steps_065000_itrs_0.999_ema/*0.png /hdd/dongjun/EighthArticleExperimentalResults/AFHQ/stroke/ctm_stroke_sampler_40_steps_065000_itrs_0.999_ema

nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=superres --sampling_steps=4 --device_id=1 --gamma=0.9 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=superres --sampling_steps=4 --device_id=2 --gamma=0.5 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=superres --sampling_steps=4 --device_id=3 --gamma=0.000001 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=1 --gamma=0.99 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=2 --gamma=0.98 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=3 --gamma=0.97 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=4 --gamma=0.96 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=5 --gamma=0.95 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=6 --gamma=0.94 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=7 --gamma=0.93 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=0 --gamma=0.92 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=1 --gamma=0.91 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=2 --gamma=0.9 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=3 --gamma=0.8 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=4 --gamma=0.7 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=5 --gamma=0.6 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=6 --gamma=0.5 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=7 --gamma=0.4 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=0 --gamma=0.3 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=1 --gamma=0.2 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=2 --gamma=0.1 > log.txt 2>&1 &
nohup python application_sample.py $MODEL_FLAGS --ref_image_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/pixabay_cat_004832.png --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=40 --eval_num_samples=40 --stochastic_seed=False --save_format=png --use_MPI=True --training_mode=ctm --sampler=inpainting --sampling_steps=40 --device_id=3 --gamma=0.00000000000001 > log.txt 2>&1 &





nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=1 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=2 --device_id=1 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=4 --device_id=2 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=40 --device_id=3 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.5 --generator_type=determ --sampling_steps=2 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.5 --generator_type=determ --sampling_steps=4 --device_id=1 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.5 --generator_type=determ --sampling_steps=40 --device_id=2 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=2 --device_id=3 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=4 --device_id=4 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=40 --device_id=5 --training_mode=ctm > log.txt 2>&1 &

nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=1 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=2 --device_id=1 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=4 --device_id=2 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=40 --device_id=3 --training_mode=ctm > log.txt 2>&1 &

nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=1 --device_id=0 --training_mode=edm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=2 --device_id=1 --training_mode=edm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=4 --device_id=2 --training_mode=edm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/DM/ema_0.999_065000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=heun --sampling_steps=40 --device_id=3 --training_mode=edm > log.txt 2>&1 &


nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_015000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=1 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_015000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=2 --device_id=1 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_015000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=4 --device_id=2 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_015000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=exact --sampling_steps=40 --device_id=3 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_015000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=2 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_015000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=4 --device_id=7 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_015000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=40 --device_id=6 --training_mode=ctm > log.txt 2>&1 &

nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_025000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=40 --device_id=0 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_035000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=40 --device_id=1 --training_mode=ctm > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/AFHQ/CTM_with_adaptive_M39_v2/ema_0.999_045000.pt --batch_size=16 --eval_num_samples=160 --stochastic_seed=False --save_format=npz --use_MPI=True --sampler=gamma_multistep --gamma=0.999999999 --generator_type=determ --sampling_steps=40 --device_id=2 --training_mode=ctm > log.txt 2>&1 &